## Pakiety Matematyczne - wykład 3

<img src="DzienDobry.jpg">

In [1]:
import numpy as np

## Lista a np.array (wektor, macierz)

In [2]:
x=[1,2,3,4]
print(2*x)
X=np.array([1,2,3,4])
print(2*X)

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


In [3]:
y=[3,4,0,1]
print(x-y)

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [4]:
print(np.array(x)-y)
print(x-np.array(y))
print(np.array(x)-np.array(y))

[-2 -2  3  3]
[-2 -2  3  3]
[-2 -2  3  3]


In [5]:
print(x*y)

TypeError: can't multiply sequence by non-int of type 'list'

In [6]:
X=np.array(x)
Y=np.array(y)
print("X =",X)
print("Y =",Y)
print("X*Y =",X*Y)

X = [1 2 3 4]
Y = [3 4 0 1]
X*Y = [3 8 0 4]


In [7]:
A=np.array([[1,2],[3,4]])
B=np.array([[3,4],[0,1]])
A*B

array([[3, 8],
       [0, 4]])

In [8]:
print("X.dot(Y) =",X.dot(Y))

X.dot(Y) = 15


In [11]:
A=np.array([[1,2],[3,4]])
print("A =\n",A)
print("A^T =\n",A.transpose())

A =
 [[1 2]
 [3 4]]
A^T =
 [[1 3]
 [2 4]]


In [12]:
print("det(A) =",np.linalg.det(A))

det(A) = -2.0000000000000004


In [15]:
X=np.array([1,2,3,4])
#Z=X  # niezupełnie o to zwykle chodzi
Z=X.copy()
#Z=np.array(X)
Z[1]=123
print(Z)
print(X)

[  1 123   3   4]
[1 2 3 4]


### Filtry

In [16]:
help(np.random.rand)

Help on built-in function rand:

rand(...) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Examples
    --------
    >>> np.random.rand(3,2)
    arra

In [60]:
X=np.random.rand(100)
#X[0]=0.5
Z=X.copy()

In [62]:
#%%timeit

#print(X)
# to poniżej można uzyskać łatwiej w jednej linijce (jak?), 
# ale chodzi o ilustrację filtrów
X[X<=0.5]=-1
X[X>0.5]=1
#print(X)

In [57]:
#%%timeit
# To samo łatwiej (Państwo dyktujecie na wykładzie):

#print(Z)
ZZ=2*np.round(Z)-1
#print(ZZ)
#print("Sprawdźmy, czy mamy to samo:", X==ZZ)
#lub lepiej:
print("Czy to samo: ",(X==ZZ).all())


Czy to samo:  True


In [63]:
# suma skumulowana (czyli W[i]=X[0]+X[1]+...+X[i])
W=np.cumsum(X)
print(X)
print(W)

[ 1. -1.  1.  1. -1. -1.  1.  1. -1.  1. -1. -1.  1. -1.  1.  1. -1. -1.
  1.  1.  1. -1.  1. -1. -1.  1.  1.  1.  1.  1.  1. -1. -1.  1.  1. -1.
 -1.  1.  1. -1. -1. -1.  1. -1.  1. -1. -1.  1.  1. -1. -1.  1. -1.  1.
  1. -1. -1. -1. -1.  1. -1.  1.  1.  1.  1.  1. -1. -1. -1.  1. -1. -1.
 -1. -1. -1. -1.  1. -1. -1.  1. -1. -1.  1.  1. -1. -1.  1.  1. -1. -1.
  1. -1.  1.  1.  1. -1.  1.  1. -1. -1.]
[ 1.  0.  1.  2.  1.  0.  1.  2.  1.  2.  1.  0.  1.  0.  1.  2.  1.  0.
  1.  2.  3.  2.  3.  2.  1.  2.  3.  4.  5.  6.  7.  6.  5.  6.  7.  6.
  5.  6.  7.  6.  5.  4.  5.  4.  5.  4.  3.  4.  5.  4.  3.  4.  3.  4.
  5.  4.  3.  2.  1.  2.  1.  2.  3.  4.  5.  6.  5.  4.  3.  4.  3.  2.
  1.  0. -1. -2. -1. -2. -3. -2. -3. -4. -3. -2. -3. -4. -3. -2. -3. -4.
 -3. -4. -3. -2. -1. -2. -1.  0. -1. -2.]



#### Czy po potasowaniu 13 ponumerowanych kart któraś będzie na tym samym miejscu?

In [67]:
Karty=np.array(range(1,14))
Potasowane=np.random.permutation(Karty)
print(Karty)
print(Potasowane)
(Karty==Potasowane).any()

[ 1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 6  5  8 12 10 11  9  2  4  3 13  1  7]


False

#### Liczymy "prawdopodobieństwo"?

In [87]:
N=1000
Karty=np.array(range(1,14))
print(Karty)
Potasowane=[np.random.permutation(Karty) for k in range(0,N)] # to JEST pętla
#print(Potasowane)
#print((Potasowane==Karty).any(axis=1))

#sum((Potasowane==Karty).any(axis=1))
print(sum((Potasowane==Karty).any(axis=1))/N)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13]
0.615


## Zadania wykładowe (czyli przykłady):
### 1. Oblicz "prawdopodobieństwo" wyrzucenia co najmniej dwunastu szóstek w 60 rzutach normalną symetryczną kostką do gry (N powtórzeń).
### 2. Oblicz 4*"prawdopodobieństwo", że punkt wylosowany z kwadratu wpadnie do koła wpisanego w ten kwadrat (N powtórzeń).

In [5]:
N=10000
X=np.random.randint(1,7,size=(N,60))

#print(np.sum(X==6,axis=1))
print(np.sum(np.sum(X==6,axis=1)>=12)/N)

[ 7 11  8 ...  3  9 13]
0.2906


In [25]:
N=1000000
X=2*np.random.rand(N)-1
Y=2*np.random.rand(N)-1
print(4*sum(X*X+Y*Y<=1)/N)


3.1405


In [23]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

In [88]:
help(np.random.permutation)

Help on built-in function permutation:

permutation(...) method of numpy.random.mtrand.RandomState instance
    permutation(x)
    
    Randomly permute a sequence, or return a permuted range.
    
    If `x` is a multi-dimensional array, it is only shuffled along its
    first index.
    
    .. note::
        New code should use the ``permutation`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    x : int or array_like
        If `x` is an integer, randomly permute ``np.arange(x)``.
        If `x` is an array, make a copy and shuffle the elements
        randomly.
    
    Returns
    -------
    out : ndarray
        Permuted sequence or array range.
    
    See Also
    --------
    Generator.permutation: which should be used for new code.
    
    Examples
    --------
    >>> np.random.permutation(10)
    array([1, 7, 4, 3, 0, 9, 2, 5, 8, 6]) # random
    
    >>> np.random.permutation([1, 4, 