# NumPy
NumPy (czyli Numerical Python) jest podstawową biblioteką w Pythonie wykorzystywaną do obliczeń naukowych. Pakiet NumPy pozwala między innymi na wykonywanie wydajnych operacji na macierzach. NumPy może być używany jako darmowa alternatywa dla MATLABa.

In [1]:
import numpy as np

### Arrays
Array to tablica wartości, <u>tego samgeo typu!</u>. Arrays są mutowalne. 

In [2]:
# podstawowym obiektem jest np.array()

a = np.array([1, 2, 3, 4, 5])
A = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])

print("Wektor 'a'\n",a)
print("Macierz 'A'\n",A)
print()

print(type(a))  # Wyświetla "<class 'numpy.ndarray'>"
print(A.shape)  # Wyświetla "(3,3)"
print(A[0,1])   # Wyświetla "2"
print(A[:,2])   # Wyświetla "[3 6 9]"
print(A[:2,1:]) # Wyświetla "[[2 3], [5 6]]"
print(A.T)      # Transpozycja macierzy A

Wektor 'a'
 [1 2 3 4 5]
Macierz 'A'
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

<class 'numpy.ndarray'>
(3, 3)
2
[3 6 9]
[[2 3]
 [5 6]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [3]:
B1 = np.zeros((2,3))
B2 = np.ones((3,4))

print(B1)
print(B2)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
B3 = np.full((3,3), 3.14)
B4 = np.eye(5)

print(B3)
print(B4)

[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [5]:
B5 = np.arange(10)

print(B5)
print(B5.reshape(2,5))           # Zmieniamy "kształt" macierzy
print(B5.reshape(2,5).flatten()) # "Wypłaszczamy" macierz do jednego wymiaru

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [6]:
C = np.arange(1,9).reshape(2,2,2)

print(C)
print(C.shape) # trójwymiarowa macierz

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [7]:
B6 = np.arange(1,9,0.1)
print(B6)

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7
 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5
 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3
 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1
 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9]


In [8]:
A = np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])

B = np.array([[1, 20, 30],
            [40, 50, 60],
            [70, 80, 90]])

print(A + B)
print(A - B)
print(A*B)
print(A.dot(B))
print(2**A)
print(A/B)

[[ 2 22 33]
 [44 55 66]
 [77 88 99]]
[[  0 -18 -27]
 [-36 -45 -54]
 [-63 -72 -81]]
[[  1  40  90]
 [160 250 360]
 [490 640 810]]
[[ 291  360  420]
 [ 624  810  960]
 [ 957 1260 1500]]
[[  2   4   8]
 [ 16  32  64]
 [128 256 512]]
[[1.  0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]]


In [9]:
studenci = np.array([["student1", "5"],
                  ["student2", "4"],
                 ["student3", "3.5"]])

print(studenci)
print(studenci)

[['student1' '5']
 ['student2' '4']
 ['student3' '3.5']]
[['student1' '5']
 ['student2' '4']
 ['student3' '3.5']]


#### Argumet dtype

In [10]:


liczby = np.array([[1,2,3],
                   [4,5,6],
                    [7,8,9]], dtype=np.float64)
print(liczby)
print("\nDtype",liczby.dtype)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Dtype float64


In [11]:
liczby = np.array([[1,2,3],
                   [4,5,6],
                    [7,8,9]], dtype=np.str)
print(liczby)

[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]


In [12]:
liczby = np.array([[1,2,0],
                   [4,5,0],
                    [7,8,0]], dtype=np.bool)
print(liczby)

[[ True  True False]
 [ True  True False]
 [ True  True False]]


In [13]:
lista = [1, 2, 3]
a = np.asarray(lista, dtype = np.float64)
print(type(lista), type(a))
print(a)

<class 'list'> <class 'numpy.ndarray'>
[1. 2. 3.]


### Iteracje po arrays

In [14]:
macierz = np.arange(0,60,5).reshape(3,4)

for v in macierz: # pętla po wierszach
    print(v)

[ 0  5 10 15]
[20 25 30 35]
[40 45 50 55]


In [15]:
for v in np.nditer(macierz): # pętla po elementach macierzy
    print(v)

0
5
10
15
20
25
30
35
40
45
50
55


### Kopiowanie i sortowanie

Kopiowanie można rozróżnić na płykie (ndarray.view() ) i głębokie (ndarray.copy()). Wycinek macierzy jest traktowany jako widok ( ndarray.view()). Zmiana elemntu w widoku powoduje zmianę elemnetu w głównej macierzy.

In [16]:
macierz = np.random.randint(1,20,size=(3,4))
print(macierz)
macierz2 = macierz.copy() # kopijujemy macierz 'macierz'

macierz.sort() # sortowanie po wierszach
print(macierz)
macierz.sort(axis=0) # sortowanie po kolumnach
print(macierz)
print(macierz2)

[[15  9  2  3]
 [ 2 11 16  7]
 [ 5  3  9  9]]
[[ 2  3  9 15]
 [ 2  7 11 16]
 [ 3  5  9  9]]
[[ 2  3  9  9]
 [ 2  5  9 15]
 [ 3  7 11 16]]
[[15  9  2  3]
 [ 2 11 16  7]
 [ 5  3  9  9]]


In [17]:
macierz = np.random.randint(1,20,size=(3,4))
print(macierz)

print(macierz.argsort()) # sortowanie po wierszach, zwracamy macierz indeksów posortowanych elementów

[[ 5 10  6  7]
 [ 5 13 10  3]
 [15 15 12 17]]
[[0 2 3 1]
 [3 0 2 1]
 [2 0 1 3]]


### Boolean array

In [18]:
A = np.arange(1,10).reshape(3,3)

print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
print(A > 5)
print(np.logical_not(A > 5))

[[False False False]
 [False False  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True False]
 [False False False]]


In [20]:
print(A[A>5])

[6 7 8 9]


In [21]:
print(A[(A>3) & (A%2==0)])

[4 6 8]


In [22]:
warunek = (A>3) & (A%2==0)
print(np.extract(warunek, A))

[4 6 8]


### Przydatne funkcje matematyczne i nie tylko

In [23]:
v = np.arange(10)
omega = np.pi/2

print(np.sin(omega*v))
print(np.cos(omega*v))
print(np.exp(v))

[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00
 -2.4492936e-16  1.0000000e+00  3.6739404e-16 -1.0000000e+00
 -4.8985872e-16  1.0000000e+00]
[ 1.0000000e+00  6.1232340e-17 -1.0000000e+00 -1.8369702e-16
  1.0000000e+00  3.0616170e-16 -1.0000000e+00 -4.2862638e-16
  1.0000000e+00  5.5109106e-16]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [24]:
A = np.arange(9).reshape(3,3)
A[2,1] = -1
n, m = A.shape
print(A)

print(A.sum())
print(A.sum(axis=0)) # suma po kolumnach
print(A.max())       # maksymalny element
print(A.argmin())    # pozycja minimalnego elemeny w macierzy A

x = A.argmin()//n
y = A.argmin() - n*x

print(A[x, y] == A.min())

print(np.mean(A))

[[ 0  1  2]
 [ 3  4  5]
 [ 6 -1  8]]
28
[ 9  4 15]
8
7
True
3.111111111111111


In [25]:
# równo rozmieszczone liczby
t = np.linspace(0, 10, 100)
print(t)

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

## hstack i vstack

In [26]:
wiersz1 = np.array([[1, 2, 3]]) # Macierz 1x3
wiersz2 = np.array([[4, 5, 6]]) # Macierz 1x3

print(np.hstack((wiersz1, wiersz2)))
print(np.vstack((wiersz1, wiersz2)))

[[1 2 3 4 5 6]]
[[1 2 3]
 [4 5 6]]


In [27]:
kolumna1 = np.array([[1],[2], [3]])  # Macierz 3x1 
kolumna2 = np.array([[4], [5], [6]]) # Macierz 3x1

print(np.hstack((kolumna1, kolumna2)))
print(np.vstack((kolumna1, kolumna2)))

[[1 4]
 [2 5]
 [3 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


Funkce *np.hsplit(macierz, v)* i *np.vsplit(macierz, v)* dzięlą *macierz* horyzontalnie lub wertykalnie względem kolumny lub wiersza *v* (*v* może też być wektorem). Dodatkowo warto zapoznać się z dzaiłaniem funkcji *np.concatenate* oraz *np.split*.

#### np.vectorize()
Zauważ, że funkce matematyczne np.sin(), np.exp(), ..., znajdujące się w bibliotece NumPy są zwektoryzowane, tzn. mogą przyjmować sekwencje danych (lub nawet macierze) jako argument. Aby zwektoryzować własną funkcję używamy funkcji (lub dekoratora) np.vectorize.

In [28]:
kwadraty = lambda x: x%2
kwadraty2 = np.vectorize(kwadraty)

t = (2, 3, 9)

print(kwadraty(9))
print(kwadraty2(9))
print(kwadraty2(t))
print(kwadraty(t))

1
1
[0 1 1]


TypeError: unsupported operand type(s) for %: 'tuple' and 'int'

#### numpy.random

In [29]:
x = np.random.random() # liczba losowa z przeciału [0,1)
print(x)

y = np.random.random()
print(y)

0.869229996031621
0.6540927975708454


In [30]:
# funkcja seed() inicjalizuje generator liczb losowych
# ustawiając ziarno na pewną wartość

np.random.seed(123) 
x = np.random.random() 
print(x)
np.random.seed(123)

y = np.random.random()
print(y)

0.6964691855978616
0.6964691855978616


In [31]:
v1 = np.random.randint(1,20,10)
v2 = np.random.sample((3,4)) # macierz elementów losowych z [0,1)
v3 = np.random.choice(range(10),size=4, replace=False)

v4 = np.arange(10)
np.random.shuffle(v4)

print(v1)
print(v2)
print(v3)
print(v4)

[ 3  3  7 18 11  2  1 18 16 10]
[[0.40101756 0.62731701 0.32415089 0.24475928]
 [0.69475518 0.5939024  0.63179202 0.44025718]
 [0.08372648 0.71233018 0.42786349 0.2977805 ]]
[8 0 2 5]
[7 5 6 8 9 3 0 4 1 2]
